all:
	gcc ansi.c game_engine.c graphics.c hw_input.c hw_LED.c hw_time.c hw_sound.c lut.c physics.c reflexball.c util.c intro.c gui.c hw_flash.c sound_lib.c game_data.c story.c charset.c -o ../../build/reflexball
	xterm -geometry 258x104 -fa 'Courier' -fs 4 -en 'POSIX' -bg 'black' -fg 'white' -e /Users/mathiasbredholt/documents/reflexball/build/reflexball