all:
	gcc ansi.c game_engine.c graphics.c hw_input.c hw_LED.c hw_time.c levels.c lut.c physics.c reflexball.c util.c intro.c shop.c menu.c -o ../../build/reflexball
	xterm -geometry 258x104 -fa 'Perfect DOS VGA 437' -en 'C' -fs 5 -bg 'black' -fg 'white' -e /Users/mathiasbredholt/documents/reflexball/build/reflexball
