

#if defined(_Z8F6403)
rom char story[63][49] =
#else
const char story[63][49] =
#endif
{
	"dokuu",
	"oh no boss",
	"theres an asteroid field",
	"its blocking our way past dokuu",
	"prepare the balls for max bounciness",
	"alderaan",
	"phew that was a close one",
	"we almost lost all our balls",
	"what is this",
	"oh no boss",
	"an evil alderaan has appeared",
	"what are your orders",
	"tatoiine",
	"finally",
	"lets hope were safe",
	"oh no boss",
	"a huge monster just jumped",
	"in to weapons range",
	"and its opening fire",
	"boss",
	"the horrors of space travel",
	"surely we must be safe now",
	"oh no boss",
	"its the feared pirate queen",
	"darth vader",
	"somewhere unknown",
	"argh boss",
	"destroying vaders ship has",
	"warped the space time continuum",
	"were being sucked in to a new dimension",
	"and its filled with generic arkanoid levels",
	"good thing we brought our best balls",
	"pub at the end of the universe",
	"wow boss we made it",
	"we safely returned to normal 2 dimensional space",
	"but where are we",
	"i sure could go for some food",
	"oh look its the pub at the end of the universe",
	"boss",
	"they are out of hotdogs",
	"welcome to the glorious",
	"tale of commander boss",
	"the pilot of the amazing",
	"striker",
	"a ship capable of bouncing",
	"a ball made of pure energy",
	"a ship that supports the ",
	"best weaponry the universe",
	"if you have the coin",
	"unfortunately you have none",
	"luckily space is filled",
	"with blocks full of coin",
#if defined(_Z8F6403)
	"use the command stick",
#else
	"use the command keys",
#endif
	"to control the striker",
#if defined(_Z8F6403)
	"and use the buttons to",
#else
	"use a and d to",
#endif
	"navigate the menus",
	" ",
	"buy upgrades in the shop",
	" ",
	"be careful you dont",
	"run out of energy",
	" ",
	"good luck"


	// "welcome to the glorious",
	// "tale of commander boss",
	// "a grand adventurer",
	// "pilot of the striker",
	// "a ship capable of bouncing",
	// "balls made of pure energy",
	// "a ship that supports the ",
	// "most advanced weaponry",
	// "in the universe",
	// "if you can pay",
	// "unfortunately",
	// "you are dirt poor",
	// "better go mining and hope",
	// "for some treasure",
	// "theres gold in them blocks",
	// "use the command stick",
	// "use a and d",
	// "to control the striker",
	// "to navigate the menus",
	// "use the buttons",
	// "use a and d",
	// "buy upgrades for the",
	// "weapons and the striker",
	// "in the shop",
	// "be careful you dont",
	// "run out of energy",
	// "good luck",
	// "press any key to continue"

};