#if defined(_Z8F6403)

rom char story[63][49] =

#else

char story[63][49] =

#endif
{
	"dokuu",
	"oh no boss",
	"theres an asteroid field",
	"its blocking our way past dokuu",
	"prepare the balls for max bounciness",
	"alderaan",
	"phew that was a close one",
	"we almost lost all our balls",
	"what is this",
	"oh no boss",
	"an evil alderaan has appeared",
	"what are your orders",
	"tatoiine",
	"finally",
	"lets hope were safe",
	"oh no boss",
	"a huge monster just jumped",
	"in to weapons range",
	"and its opening fire",
	"boss",
	"darth vader",
	"oh the horrors of space travel",
	"surely we must be safe now",
	"oh no boss",
	"its the feared pirate queen",
	"darth vader",
	"somewhere unknown",
	"argh boss",
	"destroying vaders ship has",
	"warped the space time continuum",
	"were being sucked in to a new dimension",
	"and its filled with generic arkanoid levels",
	"good thing we brought our best balls",
	"pub at the end of the universe",
	"wow boss we made it",
	"we safely returned to normal 2 dimensional space",
	"but where are we",
	"i sure could go for some food",
	"oh look its the pub at the end of the universe",
	"boss",
	"they are out of hotdogs",
	"you are commander boss",
	"your ship is the striker",
	"capable of boucing balls",
	"created by pure energy",
	"equipped with powerful",
	"weaponry",
	"lasers more powerful than",
	"the sun",
	"rockets capable of removing",
	"entire planets in a second",
	" ",
	"your only weakness",
	"is  your incompetent minion",
	"who just sold your weapons",
	"to the local hotdog vendor",
	"luckily he did not know how",
	"to remove the ultra 11",
	"elite ball bouncer",
	" ",
	"the only way is to search for",
	"glorious treasure"

};